# The API Project
In this API project, we've decided to select a random API from the RapidAPI marketplace to explore and get a hands on experience on how to **Ingest/Extract Data** from an API source.

We've decided to go with a YouTube API from the RapidAPI marketplace.
The API retrieves many types of data from Youtube.

Here's the Youtube API provider link: 
https://rapidapi.com/Glavier/api/youtube138/playground/apiendpoint_b2210da2-97ee-4448-b916-c8b83789df5c

1. Create an account on RapidAPI.com. It is free!

2. Open the link to the API provider. Copy the link above.

    ***YOU WILL HAVE TO SUBSCRIBE TO THIS API PROVIDER TO CONTINUE***

    So click the "**Subscribe to Test**" blue button at the top of the **RIGHT Panel**.

In the YouTube API provider page:

3. Look to the **LEFT Panel** to discover the various endpoints the API provider offers.

    In the "**Channel**" category, there are many endpoints BUT we're going to use the "*GET Channel Videos*" endpoint. So, click on: **>> Channel** > **GET Channel Videos**

4. Look to the **RIGHT Panel** to see the sample *Code Snippet* for your choosen endpoint.
Click the "**Target:**" dropdown and select '*Python*'
Click the "**Client:**" dropdown and select '*Requests*'

The entire *Code Snippet* you see is what we're going to need in this project.

***NOTE:*** Ideally in a real world data engineering project, your project manager should be able to provide you with most of the API details you will need like this code snippet.

## 1. Data Ingestion/Extraction with API

In [159]:
# Importing our needed python packages
import requests
import pandas as pd

In [ ]:

# Bringing entire Code Snippet from RapidAPI

url = "https://youtube138.p.rapidapi.com/channel/videos/"

querystring = {"id":"UCJ5v_MCY6GNUBTO8-D3XoAg","filter":"videos_latest","hl":"en","gl":"US"}

headers = {
	"x-rapidapi-key": "950922b3b4mshf8fa19a1a80c9bep121817jsne868362a71bc",
	"x-rapidapi-host": "youtube138.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'contents': [{'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 179, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/x8zrTAP8Ivk/mqdefault_6s.webp?du=3000&sqp=CI-Bz8sG&rs=AOn4CLCJURAPZdRG0_qnSZBei_NvcOKS6A', 'width': 320}], 'publishedTimeText': '3 hours ago', 'stats': {'views': 12333}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/x8zrTAP8Ivk/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB_U2b_yN_GqY_j-Rh7kz5tzX0l6w', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/x8zrTAP8Ivk/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDTftahiM-BmldzU9Gb3p5SGpWz9w', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/x8zrTAP8Ivk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD8EyuR4sHWLsyg0Y7pbSKs5JQB5Q', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/x8zrTAP8Ivk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAalLY2cF0VQg28j9N_rMSi73ptTw', 'width': 336}], 'title': 'Cody Rhodes and Jacob Fatu head for battle: WWE Now, Jan. 23, 2026', 'videoId': 'x8zrTAP8Ivk'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 870, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/uurCfC_HHgU/mqdefault_6s.webp?du=3000&sqp=CNm2z8sG&rs=AOn4CLCjys2ni5z9GmpqTYwE_gkeyyXACA', 'width': 320}], 'publishedTimeText': '6 hours ago', 'stats': {'views': 79739}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/uurCfC_HHgU/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBhlwKRSLSJR2w0ZHjzPAVwgIiCeg', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/uurCfC_HHgU/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLC881e4bY5pYNzFLVKrAjIgG3_SvA', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/uurCfC_HHgU/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDqDlvg45iINSfGRF7q4i0BQ18MnA', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/uurCfC_HHgU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDrJBGZ9EReCrBUwxpxhbEtWCrxdw', 'width': 336}], 'title': 'FULL MATCH: Randy Orton vs. Drew McIntyre: Saturday Night’s Main Event, July 12, 2025', 'videoId': 'uurCfC_HHgU'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 2040, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/iS9k9IOD65A/mqdefault_6s.webp?du=3000&sqp=CKCgz8sG&rs=AOn4CLBFtQU82VRF5nas4q9qe6_k04ylEA', 'width': 320}], 'publishedTimeText': '7 hours ago', 'stats': {'views': 81698}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/iS9k9IOD65A/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCDcFVdpvOowFVFLtlLfygyvTjfzg', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/iS9k9IOD65A/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAl4WYDwfvCoUEiSYaX7yRAJGNWJA', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/iS9k9IOD65A/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDUW063_quaSYDWjJiEzJceTVQoSw', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/iS9k9IOD65A/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBqY3zn3Gzy_8riq_CyeQc6KkOAOg', 'width': 336}], 'title': 'Funniest Royal Rumble moments of all time: WWE Playlist', 'videoId': 'iS9k9IOD65A'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 196, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/QfWVpBzSZsA/mqdefault_6s.webp?du=3000&sqp=CKCVz8sG&rs=AOn4CLCHATfDrzi5d5tDpKipd7emm3waxw', 'width': 320}], 'publishedTimeText': '1 day ago', 'stats': {'views': 31356}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/QfWVpBzSZsA/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBI62bBm1CjMdwqTKkA5bZ5tIV_hg', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/QfWVpBzSZsA/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLD1ANCEG4omUR194w47be8CncVMig', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/QfWVpBzSZsA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB7INpDpui_yL0hM3-M78wqAQImgQ', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/QfWVpBzSZsA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCK3PUmx_JObYhj9RNHVUZuTc5zfw', 'width': 336}], 'title': 'Karmen Petrovic and Kali Armstrong battle in Evolve: WWE Evolve highlights, Jan. 21, 2026', 'videoId': 'QfWVpBzSZsA'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 1297, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/2MvyudXO0ew/mqdefault_6s.webp?du=3000&sqp=CJSpz8sG&rs=AOn4CLDrPGp8dzg_aEAmzGIlNG445Xx-5w', 'width': 320}], 'publishedTimeText': '1 day ago', 'stats': {'views': 75266}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/2MvyudXO0ew/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBrZ0klGmjCnefHb77Rc7VsKbv7vw', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/2MvyudXO0ew/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAe8E1V6N-25O9Hrf0UwxKroTgsHA', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/2MvyudXO0ew/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDHfnOGRdX6ZyR4-ALsOZr_i6UVog', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/2MvyudXO0ew/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAI1zfKmAceJUNDggQ8ZHCYs8Z-Ng', 'width': 336}], 'title': 'FULL MATCH: AJ Styles vs. Shinsuke Nakamura | WWE Title Match: Greatest Royal Rumble 2018', 'videoId': '2MvyudXO0ew'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 2334, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/W4Fm008NKzk/mqdefault_6s.webp?du=3000&sqp=CJKTz8sG&rs=AOn4CLAt4QxHUXqbLpLsuj0jgJdodRZqfg', 'width': 320}], 'publishedTimeText': '1 day ago', 'stats': {'views': 198970}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/W4Fm008NKzk/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBsqX4jDUyaGPlv3k0v8_yRdcxNBg', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/W4Fm008NKzk/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBtzxPqlamClsBFqFI_wHs5fWAK9A', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/W4Fm008NKzk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCQPZVf7IT-jNsdg-XR6S9yRCEUMw', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/W4Fm008NKzk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBDTjaTEJwNJ99kXuQfRf9ltOhwTA', 'width': 336}], 'title': 'Massive pull-apart brawls: WWE Playlist', 'videoId': 'W4Fm008NKzk'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 522, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/FBpiehKFPeg/mqdefault_6s.webp?du=3000&sqp=CMCsz8sG&rs=AOn4CLBmB4fEeP2TvtPK2gRzibEFPeLvFw', 'width': 320}], 'publishedTimeText': '2 days ago', 'stats': {'views': 46789}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/FBpiehKFPeg/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDdEPs3QRjMzWgxp0zUf80W6AMgvg', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/FBpiehKFPeg/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAufZszVbbB5efBtr_XsBRoy-tEoA', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/FBpiehKFPeg/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCSEJb-MZd78Rq07YOgaaUhDzFf1Q', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/FBpiehKFPeg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDcfG9Y-kqNVEAF7vBm1wn70-Ha6g', 'width': 336}], 'title': 'Top 10 WWE NXT moments: WWE Top 10, Jan. 20, 2026', 'videoId': 'FBpiehKFPeg'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 5413, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/U0-D_wSStlk/mqdefault_6s.webp?du=3000&sqp=CK-Yz8sG&rs=AOn4CLA9lME0TjyyZdHDnusipkTGesJrMA', 'width': 320}], 'publishedTimeText': '2 days ago', 'stats': {'views': 1694720}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/U0-D_wSStlk/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA4kvaIsgw1eRvFDhpsNDPCpdGzGQ', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/U0-D_wSStlk/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDPicREPS3TLVGqjNxk27bE7i034Q', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/U0-D_wSStlk/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDZHooa738eilWl8uWdZRbMU4Kt2g', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/U0-D_wSStlk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLABPPYBWw_3PJfJr08QZWOnin16ng', 'width': 336}], 'title': 'FULL MATCH: 2025 Men’s Royal Rumble Match: Royal Rumble 2025', 'videoId': 'U0-D_wSStlk'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 524, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/qWqvsTq2OTg/mqdefault_6s.webp?du=3000&sqp=CLiZz8sG&rs=AOn4CLDF4F2-lQYjtIlFz6d3VALpFqbluw', 'width': 320}], 'publishedTimeText': '2 days ago', 'stats': {'views': 161016}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/qWqvsTq2OTg/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAeCqLqbje-nBQUBmii41uga8jRmQ', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/qWqvsTq2OTg/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBYRMusqbiZJePTIRNVOT3xVcLYZw', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/qWqvsTq2OTg/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAvr9IZHzQVSzGizssvu6AGLNpdtA', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/qWqvsTq2OTg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBcG3x2-pItGY5FPDmQLbvSjElpdg', 'width': 336}], 'title': 'Full NXT highlights: Jan. 20, 2026', 'videoId': 'qWqvsTq2OTg'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 608, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/4s0XAeLlDUU/mqdefault_6s.webp?du=3000&sqp=CM-Qz8sG&rs=AOn4CLDCQs-ey3EDNyoJDOkkrGY9MHVwJQ', 'width': 320}], 'publishedTimeText': '2 days ago', 'stats': {'views': 181974}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/4s0XAeLlDUU/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCQJcS7GE6ZXUOYPffFiV5z34d7wA', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/4s0XAeLlDUU/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBi4VJlytP6Zllgy3ktBzJUmKOTOA', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/4s0XAeLlDUU/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAl-oFGbLFWbelOHVA9NTxM4eP64A', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/4s0XAeLlDUU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDlsiZ_TBqk1xW-IzVNV02Yzw0BCw', 'width': 336}], 'title': 'FULL MATCH: ZaRuca vs. WrenQCC vs. Fatal Influence | Triple Threat Match: NXT, Jan. 20, 2026', 'videoId': '4s0XAeLlDUU'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 197, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/8tuPEKQWCjs/mqdefault_6s.webp?du=3000&sqp=CJKrz8sG&rs=AOn4CLCJ2lMwbOFpnNkTOdtEZKOG-U6QmQ', 'width': 320}], 'publishedTimeText': '2 days ago', 'stats': {'views': 78597}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/8tuPEKQWCjs/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLDPKnujp9UqKJplwi7UbWxhzQOnFw', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/8tuPEKQWCjs/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCTp1Xy1KG6pPWmH-tqB1nm6ZeKpQ', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/8tuPEKQWCjs/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCO5tC-C3bMwjY7p65H2pSFw7CNcw', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/8tuPEKQWCjs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCP9MY24tTtNCB8zUpfUBT3kMpXYw', 'width': 336}], 'title': 'DEVELOPING: Tony D’Angelo gets arrested: NXT highlights, Jan. 20, 2026', 'videoId': '8tuPEKQWCjs'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 188, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/rN1cQM5i_Yw/mqdefault_6s.webp?du=3000&sqp=CLitz8sG&rs=AOn4CLA8Dg3d0KUlKX8pSDU4bdIw1JnUzA', 'width': 320}], 'publishedTimeText': '2 days ago', 'stats': {'views': 36029}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/rN1cQM5i_Yw/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCjys4dBxWTrGyxTFJFGvf7DcYUQw', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/rN1cQM5i_Yw/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAacG3aJqVRgUxZghKtSmK54KuYfg', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/rN1cQM5i_Yw/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBGsvTvbWbtP1YdhdJji_g0R_k_8w', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/rN1cQM5i_Yw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBfid6Qxu3l70rncInj71oyRXqE5g', 'width': 336}], 'title': 'Shiloh Hill and Sean Legacy qualify for NXT Title Ladder Match: NXT highlights, Jan. 20, 2026', 'videoId': 'rN1cQM5i_Yw'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 204, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/nQbH_kycEg0/mqdefault_6s.webp?du=3000&sqp=CIKVz8sG&rs=AOn4CLA2mg9PkTpTTeDekgpp1tXDtfNd5g', 'width': 320}], 'publishedTimeText': '2 days ago', 'stats': {'views': 91312}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/nQbH_kycEg0/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLBEM1C4w9RjclyaS_i_6YHeuxUgtg', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/nQbH_kycEg0/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLD09mQf874mjcYrLPU3BeyLxc7fYg', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/nQbH_kycEg0/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDtbtNFF6aYKVEsUd7ML1vPkfJKSA', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/nQbH_kycEg0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBJl2YcHW_KK5tRZPMAAjaBB6bPyw', 'width': 336}], 'title': 'Jaida Parker puts Blake Monroe on notice: NXT highlights, Jan. 20, 2026', 'videoId': 'nQbH_kycEg0'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 198, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/CqDsfqff-_Y/mqdefault_6s.webp?du=3000&sqp=CNSYz8sG&rs=AOn4CLDIxtY19-PcTwaHxF0UsnN_jT1VIg', 'width': 320}], 'publishedTimeText': '2 days ago', 'stats': {'views': 50691}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/CqDsfqff-_Y/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAggbDWVH6_6QJwYcBy43dYj91CTA', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/CqDsfqff-_Y/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCH5hPV_Kns5bfzbTaxXKYljyd4DA', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/CqDsfqff-_Y/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBNOskP0IOzghal91GbvM1cYlailA', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/CqDsfqff-_Y/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBooQLcKiupReSC0-z_2C6kES3gUA', 'width': 336}], 'title': 'Ethan Page vanquishes Elio LeFleur to retain his title: NXT highlights, Jan. 20, 2026', 'videoId': 'CqDsfqff-_Y'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 684, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/yFT1inIWDBs/mqdefault_6s.webp?du=3000&sqp=CJ-iz8sG&rs=AOn4CLCgfCmrgAbZ0EpkjNcCG6gcMFeOyw', 'width': 320}], 'publishedTimeText': '3 days ago', 'stats': {'views': 352355}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/yFT1inIWDBs/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA6BVEgVzI58usf7S1IFT-7xckgGg', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/yFT1inIWDBs/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLA3abqZdtLcMrEi8-ppUm4eAUwdUw', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/yFT1inIWDBs/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDoBACO6wLheswiaNEkv5BhjqixAw', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/yFT1inIWDBs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC0Cmz-fac90kdbwIhO-QynLPMVQQ', 'width': 336}], 'title': 'Top 10 Raw moments: WWE Top 10, Jan. 19, 2026', 'videoId': 'yFT1inIWDBs'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 3799, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/FS5UKtKI5BQ/mqdefault_6s.webp?du=3000&sqp=CJyoz8sG&rs=AOn4CLBdCrbG3lvduIlcU6kjPOuWMSCLmw', 'width': 320}], 'publishedTimeText': '3 days ago', 'stats': {'views': 83441}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/FS5UKtKI5BQ/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAeHDecqerNOgUPvkLY9VPG99p5Ug', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/FS5UKtKI5BQ/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCP3WgO0uakyjLdvS9whKFa-qCYlg', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/FS5UKtKI5BQ/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDa1AkCtKIiQg8ADWgupBH9fP8tIg', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/FS5UKtKI5BQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBfZANCvzJVminvQTOclSJ2j_Feaw', 'width': 336}], 'title': 'CM Punk and Finn Bálor deliver an instant CLASSIC: Raw Recap, Jan. 19, 2026', 'videoId': 'FS5UKtKI5BQ'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 587, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/OCaKOjkQhRI/mqdefault_6s.webp?du=3000&sqp=CMaGz8sG&rs=AOn4CLDN8l373BXp0P2ADz8BDCebemIlog', 'width': 320}], 'publishedTimeText': '3 days ago', 'stats': {'views': 617357}, 'thumbnails': [{'height': 94, 'url': 'https://i.ytimg.com/vi/OCaKOjkQhRI/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLB8Li2oz9sp3AnEm5BaP6BCRAZniA', 'width': 168}, {'height': 110, 'url': 'https://i.ytimg.com/vi/OCaKOjkQhRI/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLAQ4x_I6jXz_bwNSF6gaYbHqJ31Uw', 'width': 196}, {'height': 138, 'url': 'https://i.ytimg.com/vi/OCaKOjkQhRI/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB8ykuDW576TPiq0UjG8w5yOuP2OA', 'width': 246}, {'height': 188, 'url': 'https://i.ytimg.com/vi/OCaKOjkQhRI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBFQ-L49wimTYfPmucYUs7wUpoqfQ', 'width': 336}], 'title': 'Full Raw highlights: Jan. 19, 2026', 'videoId': 'OCaKOjkQhRI'}}, {'type': 'video', 'video': {'badges': [], 'isLiveNow': False, 'lengthSeconds': 245, 'movingThumbnails': [{'height': 180, 'url': 'https://i.ytimg.com/an_webp/nVQaGpNQa0I/mqdefaul

In [ ]:
# Creating a function to retrieve data from the API endpoint
def retrieve_youtube_data():

    # All API parameters

    # The API endpoint
    url = "https://youtube138.p.rapidapi.com/channel/videos/"

    # Optional: This is parameter that may be needed to get specific data with the endpoint. 
    querystring = {"id":"UCJ5v_MCY6GNUBTO8-D3XoAg","filter":"videos_latest","hl":"en","gl":"US"}

    # The API headers: This carries the API key and the server hosting the API data.
    # *** YOUR API KEY WILL BE DIFFERENT FROM MINE. USE YOURS FROM RapidAPI to follow along ***
    headers = {
	"x-rapidapi-key": "950922b3b4mshf8fa19a1a80c9bep121817jsne868362a71bc",
	"x-rapidapi-host": "youtube138.p.rapidapi.com"
    }

    # Retrieving data from our API: Send a GET request to the API endpoint
    # Here, we use the "requests" library we imported from the start above.
    response = requests.get(url, headers=headers, params=querystring)

    # Show the response from the API call. This will show just the status_code.
    print(response)

    # Check if the request was successful
    if response.status_code == 200:
        print("API call was successful, data retrieved.")

        # Parse the response content as JSON
        json_data = response.json()

        # The actual data from the retrieved data is in the 'contents'. List of JSON data.
        actual_data = json_data['contents']

        # Using pandas "json_normalize" function to Flatten the JSON data
        df = pd.json_normalize(actual_data) # Parsing the LIST of JSON to a DataFrame
        
        # Save the json normalized data (flat file) 
        # This will be saved as a csv file in your current project folder
        df.to_csv("raw_api_data.csv", index=False)
    else:
        # Here, you can do all possible actions as the response status_code was not "200"
        print("API call was UNSUCCESSFUL. There was an error, please investigate the issue.")

In [163]:
# Calling the function "def retrieve_youtube_data()" we created above
retrieve_youtube_data()

<Response [200]>
API call was successful, data retrieved.

### 1.1 Discovering our raw dataset

In [164]:

# Reading the raw data "raw_api_data.csv" from our project folder usind pandas
df_contents = pd.read_csv('raw_api_data.csv')

In [165]:
# Just discovering: checking the dataframe number of rows and columns
df_contents.shape

(29, 10)

In [166]:
# Just discovering: checking the dataframe columns and their names
df_contents.columns

Index(['type', 'video.badges', 'video.isLiveNow', 'video.lengthSeconds',
       'video.movingThumbnails', 'video.publishedTimeText',
       'video.stats.views', 'video.thumbnails', 'video.title',
       'video.videoId'],
      dtype='object')

In [167]:
# Just discovering: checking general info (columns, their datatypes, if any nulls, etc...)
df_contents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   type                     29 non-null     object
 1   video.badges             29 non-null     object
 2   video.isLiveNow          29 non-null     bool
 3   video.lengthSeconds      29 non-null     int64
 4   video.movingThumbnails   29 non-null     object
 5   video.publishedTimeText  29 non-null     object
 6   video.stats.views        29 non-null     int64
 7   video.thumbnails         29 non-null     object
 8   video.title              29 non-null     object
 9   video.videoId            29 non-null     object
dtypes: bool(1), int64(2), object(7)
memory usage: 2.2+ KB

In [168]:
# Sneak peak into the data itself
df_contents.head()

,type,video.badges,video.isLiveNow,video.lengthSeconds,video.movingThumbnails,video.publishedTimeText,video.stats.views,video.thumbnails,video.title,video.videoId
0,video,[],False,179,"[{'height': 180, 'url': 'https://i.ytimg.com/a...",3 hours ago,12333,"[{'height': 94, 'url': 'https://i.ytimg.com/vi...",Cody Rhodes and Jacob Fatu head for battle: WW...,x8zrTAP8Ivk
1,video,[],False,870,"[{'height': 180, 'url': 'https://i.ytimg.com/a...",6 hours ago,79739,"[{'height': 94, 'url': 'https://i.ytimg.com/vi...",FULL MATCH: Randy Orton vs. Drew McIntyre: Sat...,uurCfC_HHgU
2,video,[],False,2040,"[{'height': 180, 'url': 'https://i.ytimg.com/a...",7 hours ago,81698,"[{'height': 94, 'url': 'https://i.ytimg.com/vi...",Funniest Royal Rumble moments of all time: WWE...,iS9k9IOD65A
3,video,[],False,196,"[{'height': 180, 'url': 'https://i.ytimg.com/a...",1 day ago,31356,"[{'height': 94, 'url': 'https://i.ytimg.com/vi...",Karmen Petrovic and Kali Armstrong battle in E...,QfWVpBzSZsA
4,video,[],False,1297,"[{'height': 180, 'url': 'https://i.ytimg.com/a...",1 day ago,75209,"[{'height': 94, 'url': 'https://i.ytimg.com/vi...",FULL MATCH: AJ Styles vs. Shinsuke Nakamura | ...,2MvyudXO0ew

In [169]:
# Just discovering: checking all columns in the dataframe
df_contents.columns

Index(['type', 'video.badges', 'video.isLiveNow', 'video.lengthSeconds',
       'video.movingThumbnails', 'video.publishedTimeText',
       'video.stats.views', 'video.thumbnails', 'video.title',
       'video.videoId'],
      dtype='object')

## Data Transformation

In [143]:
# Copying our raw data to a staging dataframe.
# Remember as Data Engineers, alawys leave your raw data as it is.
df_contents_staging = df_contents.copy()

In [145]:
# Sneak peaking into our staged dataframe (the copy) by looking at just the first two rows
df_contents_staging.head(2)

,type,video.badges,video.isLiveNow,video.lengthSeconds,video.movingThumbnails,video.publishedTimeText,video.stats.views,video.thumbnails,video.title,video.videoId
0,video,[],False,179,"[{'height': 180, 'url': 'https://i.ytimg.com/a...",3 hours ago,10557,"[{'height': 94, 'url': 'https://i.ytimg.com/vi...",Cody Rhodes and Jacob Fatu head for battle: WW...,x8zrTAP8Ivk
1,video,[],False,870,"[{'height': 180, 'url': 'https://i.ytimg.com/a...",6 hours ago,73442,"[{'height': 94, 'url': 'https://i.ytimg.com/vi...",FULL MATCH: Randy Orton vs. Drew McIntyre: Sat...,uurCfC_HHgU

In [147]:
# Copying selected columns into a new dataframe
# Columns of interest to us (based on potential business questions from stakeholders)

# Sample format from ChatGPT: new_df = df[["col1", "col2", "col3"]].copy()

df_contents_staging_new = df_contents_staging[["video.isLiveNow", 
                                               "video.lengthSeconds",
                                               "video.publishedTimeText",
                                               "video.stats.views",
                                               "video.title",
                                               "video.videoId"]].copy()

In [149]:
# This new dataframe name "df_contents_staging_new" is too long. 
# Lets shorten it for easy subsequent use.

staged_df = df_contents_staging_new

In [150]:
# Sneak peaking into our NEW dataframe by looking at just the first two rows
staged_df.head(2)

,video.isLiveNow,video.lengthSeconds,video.publishedTimeText,video.stats.views,video.title,video.videoId
0,False,179,3 hours ago,10557,Cody Rhodes and Jacob Fatu head for battle: WW...,x8zrTAP8Ivk
1,False,870,6 hours ago,73442,FULL MATCH: Randy Orton vs. Drew McIntyre: Sat...,uurCfC_HHgU

In [151]:
# Moving through each column one-by-one to see what we can transform as Data Engineers
# This is to help the Data Analysts to answer possible/potential business questions

# Checking the first column in our "df_contents_staging_new" dataframe
# >>> "video.isLiveNow" column

# This checks for all unique data in that column
staged_df['video.isLiveNow'].unique()

array([False])

In [152]:
# This checks for, and counts any null values in that column
staged_df['video.isLiveNow'].isnull().value_counts()

# We can check for more issues/inconsistencies but so far, we think the column is good to go.

video.isLiveNow
False    29
Name: count, dtype: int64

In [153]:
# Checking the next column in our "df_contents_staging_new" dataframe
# >>> "video.lengthSeconds" column

# After checking, decided to add a new column "vid_length_mins" to the dataset
# This new column will be the "video.lengthSeconds" transformed in minutes
# This might be helpful to our Data Analytics team.
staged_df["vid_length_mins"] = staged_df["video.lengthSeconds"] / 60

In [154]:
# Sneak peaking into our NEW dataframe AGAIN by looking at just the first two rows
df_contents_staging_new.head(2)

,video.isLiveNow,video.lengthSeconds,video.publishedTimeText,video.stats.views,video.title,video.videoId,vid_length_mins
0,False,179,3 hours ago,10557,Cody Rhodes and Jacob Fatu head for battle: WW...,x8zrTAP8Ivk,2.983333
1,False,870,6 hours ago,73442,FULL MATCH: Randy Orton vs. Drew McIntyre: Sat...,uurCfC_HHgU,14.500000

In [155]:
# Our added column "vid_length_mins" is in 6 decimal places. Lets round it up.

# Sample format from ChatGPT: df["col_rounded"] = df["col"].round(2)
staged_df["vid_length_mins"] = (staged_df["video.lengthSeconds"] / 60).round(0)

In [157]:
# Sneak peaking into our NEW dataframe AGAIN by looking at just the first two rows
staged_df.head(2)

,video.isLiveNow,video.lengthSeconds,video.publishedTimeText,video.stats.views,video.title,video.videoId,vid_length_mins
0,False,179,3 hours ago,10557,Cody Rhodes and Jacob Fatu head for battle: WW...,x8zrTAP8Ivk,3.0
1,False,870,6 hours ago,73442,FULL MATCH: Randy Orton vs. Drew McIntyre: Sat...,uurCfC_HHgU,14.0